// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxFZMpepj88RKmewtB-c57NID_OCIJAU',
    appId: '1:991021742623:web:b6ef847fd7267fbaaa332a',
    messagingSenderId: '991021742623',
    projectId: 'vtaempanada-abb4a',
    authDomain: 'vtaempanada-abb4a.firebaseapp.com',
    storageBucket: 'vtaempanada-abb4a.appspot.com',
    measurementId: 'G-9T687NWDVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC31arMnEmmr1IvSPll7WFWzjr8bcR9EO8',
    appId: '1:991021742623:android:a0c159ed4b990e91aa332a',
    messagingSenderId: '991021742623',
    projectId: 'vtaempanada-abb4a',
    storageBucket: 'vtaempanada-abb4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_k59015emv6GHrE5mDDmq30kLcJ2wYyE',
    appId: '1:991021742623:ios:3aae6cb4e0a033beaa332a',
    messagingSenderId: '991021742623',
    projectId: 'vtaempanada-abb4a',
    storageBucket: 'vtaempanada-abb4a.appspot.com',
    iosClientId: '991021742623-f5gdnnithd3tgrstdle21kgnn4h9boca.apps.googleusercontent.com',
    iosBundleId: 'com.example.vtaempanada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_k59015emv6GHrE5mDDmq30kLcJ2wYyE',
    appId: '1:991021742623:ios:41fd2fb51ae138dfaa332a',
    messagingSenderId: '991021742623',
    projectId: 'vtaempanada-abb4a',
    storageBucket: 'vtaempanada-abb4a.appspot.com',
    iosClientId: '991021742623-r3ogh13c4mh2h4im9nelj8v856aqutih.apps.googleusercontent.com',
    iosBundleId: 'com.example.vtaempanada.RunnerTests',
  );
}
